<?php
namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class OrderController extends ApiController
{
    /**
     * @Route("/orders")
     */
    public function orders()
    {
        return $this->respond([
            [
                "id" => 1000,
                "date" => "2020-07-22 18:57:51",
                "customer" => "Hilary Greer",
                "address1" => "488-8906 Facilisis Avenue",
                "city" => "Mobile",
                "postcode" => "511162",
                "country" => "Switzerland",
                "amount" => 6093,
                "status" => "cancelled",
                "deleted" => "No",
                "last_modified" => "2020-10-16 05:35:52"
            ],
            [
                "id" => 1001,
                "date" => "2020-04-19 03:39:30",
                "customer" => "Yen Ortega",
                "address1" => "9360 Iaculis Road",
                "city" => "Coquimbo",
                "postcode" => "960096",
                "country" => "China",
                "amount" => 8545,
                "status" => "cancelled",
                "deleted" => "No",
                "last_modified" => "2020-10-21 08:16:30"
            ],
            [
                "id" => 1002,
                "date" => "2019-07-03 15:44:11",
                "customer" => "Maris Oconnor",
                "address1" => "1234 Posuere St.",
                "city" => "Acquasanta Terme",
                "postcode" => "551564",
                "country" => "Hong Kong",
                "amount" => 2609,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2019-08-29 03:02:30"
            ],
            [
                "id" => 1003,
                "date" => "2020-10-16 08:48:14",
                "customer" => "Sybill Gregory",
                "address1" => "809-4206 Nunc St.",
                "city" => "Birmingham",
                "postcode" => "M0C 9A5",
                "country" => "Moldova",
                "amount" => 3790,
                "status" => "pending",
                "deleted" => "No",
                "last_modified" => "2021-01-18 03:38:23"
            ],
            [
                "id" => 1004,
                "date" => "2020-09-02 09:26:05",
                "customer" => "Briar Lee",
                "address1" => "973-9570 Nisl Rd.",
                "city" => "Fryazino",
                "postcode" => "21109",
                "country" => "French Guiana",
                "amount" => 2470,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2020-09-09 01:45:51"
            ],
            [
                "id" => 1005,
                "date" => "2019-07-19 10:17:31",
                "customer" => "Keiko Mathews",
                "address1" => "3611 Non Rd.",
                "city" => "Chicoutimi",
                "postcode" => "26269",
                "country" => "Kiribati",
                "amount" => 7919,
                "status" => "cancelled",
                "deleted" => "No",
                "last_modified" => "2019-09-25 07:15:48"
            ],
            [
                "id" => 1006,
                "date" => "2020-09-09 02:15:01",
                "customer" => "Latifah Irwin",
                "address1" => "620-3105 Sapien Road",
                "city" => "San Pedro",
                "postcode" => "923996",
                "country" => "Cambodia",
                "amount" => 9645,
                "status" => "pending",
                "deleted" => "No",
                "last_modified" => "2019-10-05 04:21:03"
            ],
            [
                "id" => 1007,
                "date" => "2020-09-25 12:48:23",
                "customer" => "Hillary Watkins",
                "address1" => "P.O. Box 621, 5214 Nec Rd.",
                "city" => "Raurkela",
                "postcode" => "64-651",
                "country" => "Azerbaijan",
                "amount" => 6491,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2020-06-17 07:03:17"
            ],
            [
                "id" => 1008,
                "date" => "2020-10-29 04:29:02",
                "customer" => "Jena Santos",
                "address1" => "P.O. Box 304, 3464 Accumsan Av.",
                "city" => "Beaufays",
                "postcode" => "7645 IC",
                "country" => "Maldives",
                "amount" => 1207,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2020-07-14 22:11:21"
            ],
            [
                "id" => 1009,
                "date" => "2021-01-06 06:38:45",
                "customer" => "Tana Young",
                "address1" => "Ap #463-9557 Ipsum Av.",
                "city" => "Bevilacqua",
                "postcode" => "66326",
                "country" => "Lebanon",
                "amount" => 8525,
                "status" => "cancelled",
                "deleted" => "No",
                "last_modified" => "2021-01-08 10:05:11"
            ],
            [
                "id" => 1010,
                "date" => "2019-09-10 02:57:38",
                "customer" => "Madeline Lane",
                "address1" => "2409 Nunc Rd.",
                "city" => "White Rock",
                "postcode" => "Z1836",
                "country" => "Papua New Guinea",
                "amount" => 8492,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2019-06-22 09:02:42"
            ],
            [
                "id" => 1011,
                "date" => "2020-01-11 11:13:12",
                "customer" => "Ignacia Drake",
                "address1" => "170-5878 Neque Road",
                "city" => "Hull",
                "postcode" => "7350 IL",
                "country" => "Angola",
                "amount" => 8202,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2021-03-08 07:29:24"
            ],
            [
                "id" => 1012,
                "date" => "2019-10-01 14:38:27",
                "customer" => "Ciara Mayo",
                "address1" => "6487 Sem Ave",
                "city" => "Bonnyville",
                "postcode" => "22747",
                "country" => "Saudi Arabia",
                "amount" => 7639,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2019-07-23 10:28:28"
            ],
            [
                "id" => 1013,
                "date" => "2019-07-11 07:14:37",
                "customer" => "Carol Beard",
                "address1" => "Ap #800-2454 Orci. Road",
                "city" => "Providencia",
                "postcode" => "311774",
                "country" => "Aruba",
                "amount" => 5236,
                "status" => "cancelled",
                "deleted" => "No",
                "last_modified" => "2020-04-20 16:38:54"
            ],
            [
                "id" => 1014,
                "date" => "2019-07-03 15:45:50",
                "customer" => "Francesca Joyner",
                "address1" => "Ap #587-660 Erat. Street",
                "city" => "Baracaldo",
                "postcode" => "4414 MV",
                "country" => "Isle of Man",
                "amount" => 9744,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2020-11-21 14:51:51"
            ],
            [
                "id" => 1015,
                "date" => "2019-08-03 21:34:59",
                "customer" => "Charity Robertson",
                "address1" => "997-5278 Mauris Street",
                "city" => "Ternitz",
                "postcode" => "3918",
                "country" => "Philippines",
                "amount" => 1785,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2020-03-05 17:56:49"
            ],
            [
                "id" => 1016,
                "date" => "2019-10-13 10:43:04",
                "customer" => "Azalia Harvey",
                "address1" => "P.O. Box 385, 5118 Consequat Street",
                "city" => "Saint-Urbain",
                "postcode" => "504023",
                "country" => "Oman",
                "amount" => 8662,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2020-04-25 23:29:17"
            ],
            [
                "id" => 1017,
                "date" => "2020-11-13 11:11:12",
                "customer" => "Hyacinth Harrington",
                "address1" => "P.O. Box 565, 5029 Neque Street",
                "city" => "North Vancouver",
                "postcode" => "01951",
                "country" => "Sudan",
                "amount" => 3224,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2021-04-03 02:59:48"
            ],
            [
                "id" => 1018,
                "date" => "2020-09-07 21:13:15",
                "customer" => "Iris Elliott",
                "address1" => "691-1863 Duis Street",
                "city" => "Ambleside",
                "postcode" => "Y4M 1S1",
                "country" => "Canada",
                "amount" => 5150,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2020-05-08 17:04:14"
            ],
            [
                "id" => 1019,
                "date" => "2020-09-16 10:07:09",
                "customer" => "Desiree House",
                "address1" => "Ap #974-6672 Mi Rd.",
                "city" => "San Martino in Pensilis",
                "postcode" => "6145",
                "country" => "Cameroon",
                "amount" => 1531,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2020-09-05 22:12:16"
            ],
            [
                "id" => 1020,
                "date" => "2020-05-07 21:18:55",
                "customer" => "Faith Nunez",
                "address1" => "P.O. Box 352, 1955 Proin Rd.",
                "city" => "Santa Marta",
                "postcode" => "06359",
                "country" => "Western Sahara",
                "amount" => 2005,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2020-07-26 20:08:33"
            ],
            [
                "id" => 1021,
                "date" => "2021-03-04 19:04:26",
                "customer" => "Whitney Head",
                "address1" => "P.O. Box 739, 8396 Cras Rd.",
                "city" => "Tübingen",
                "postcode" => "09558",
                "country" => "Tunisia",
                "amount" => 9985,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2019-11-22 05:12:36"
            ],
            [
                "id" => 1022,
                "date" => "2021-03-10 19:43:22",
                "customer" => "Colleen Chandler",
                "address1" => "2418 Magna Rd.",
                "city" => "Kortessem",
                "postcode" => "6114",
                "country" => "Micronesia",
                "amount" => 9905,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2020-05-13 06:10:49"
            ],
            [
                "id" => 1023,
                "date" => "2019-12-29 06:48:42",
                "customer" => "Kerry Franklin",
                "address1" => "232-3004 Aliquet St.",
                "city" => "Paternopoli",
                "postcode" => "6515",
                "country" => "Faroe Islands",
                "amount" => 8060,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2021-04-25 21:36:18"
            ],
            [
                "id" => 1024,
                "date" => "2019-08-11 10:42:26",
                "customer" => "Stephanie Avila",
                "address1" => "7083 Ante Street",
                "city" => "Toledo",
                "postcode" => "4516",
                "country" => "Hong Kong",
                "amount" => 2303,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2021-05-03 14:13:53"
            ],
            [
                "id" => 1025,
                "date" => "2020-08-22 00:34:52",
                "customer" => "Shay Nicholson",
                "address1" => "P.O. Box 747, 8427 Fringilla St.",
                "city" => "Wimbledon",
                "postcode" => "13725",
                "country" => "El Salvador",
                "amount" => 4511,
                "status" => "in_production",
                "deleted" => "Yes",
                "last_modified" => "2019-05-14 03:49:30"
            ],
            [
                "id" => 1026,
                "date" => "2020-01-20 17:27:55",
                "customer" => "Kalia Gilbert",
                "address1" => "P.O. Box 912, 6881 Tempus Rd.",
                "city" => "Overland Park",
                "postcode" => "60458",
                "country" => "Marshall Islands",
                "amount" => 6581,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2020-08-10 07:06:13"
            ],
            [
                "id" => 1027,
                "date" => "2020-09-22 12:49:06",
                "customer" => "Isabella Hawkins",
                "address1" => "P.O. Box 160, 7777 Vitae Avenue",
                "city" => "Charlottetown",
                "postcode" => "91090",
                "country" => "Saint Martin",
                "amount" => 7122,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2019-09-25 10:30:42"
            ],
            [
                "id" => 1028,
                "date" => "2021-04-04 15:57:36",
                "customer" => "Nelle Hill",
                "address1" => "P.O. Box 527, 5047 Nulla Rd.",
                "city" => "Angoulême",
                "postcode" => "888573",
                "country" => "Bahamas",
                "amount" => 7678,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2019-10-15 20:12:41"
            ],
            [
                "id" => 1029,
                "date" => "2020-11-01 21:44:04",
                "customer" => "Dakota Sexton",
                "address1" => "733-3500 Ut Ave",
                "city" => "Erciş",
                "postcode" => "4508",
                "country" => "Turkmenistan",
                "amount" => 8275,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2020-05-12 20:45:47"
            ],
            [
                "id" => 1030,
                "date" => "2019-08-13 15:48:20",
                "customer" => "Minerva Beard",
                "address1" => "Ap #882-5348 Tempor Av.",
                "city" => "San Fernando",
                "postcode" => "322486",
                "country" => "Iceland",
                "amount" => 6494,
                "status" => "cancelled",
                "deleted" => "No",
                "last_modified" => "2020-04-09 06:57:26"
            ],
            [
                "id" => 1031,
                "date" => "2019-11-08 19:28:10",
                "customer" => "Hanae Curry",
                "address1" => "P.O. Box 525, 8870 Nullam Avenue",
                "city" => "Sesto al Reghena",
                "postcode" => "M9H 8A9",
                "country" => "Namibia",
                "amount" => 6943,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2021-02-02 00:37:48"
            ],
            [
                "id" => 1032,
                "date" => "2020-08-08 04:36:05",
                "customer" => "Teegan Fry",
                "address1" => "Ap #580-7426 Lectus Street",
                "city" => "Winnipeg",
                "postcode" => "R4T 6X2",
                "country" => "Martinique",
                "amount" => 3420,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2021-04-12 04:57:04"
            ],
            [
                "id" => 1033,
                "date" => "2020-02-27 20:27:25",
                "customer" => "Briar Harris",
                "address1" => "P.O. Box 132, 2239 Senectus St.",
                "city" => "Beaumaris",
                "postcode" => "12197-829",
                "country" => "Turkmenistan",
                "amount" => 5545,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2020-01-08 22:45:26"
            ],
            [
                "id" => 1034,
                "date" => "2020-09-16 05:59:25",
                "customer" => "Kylie Middleton",
                "address1" => "Ap #109-2447 Tincidunt Rd.",
                "city" => "Dipignano",
                "postcode" => "35-794",
                "country" => "Guatemala",
                "amount" => 9081,
                "status" => "pending",
                "deleted" => "No",
                "last_modified" => "2019-07-14 00:52:11"
            ],
            [
                "id" => 1035,
                "date" => "2020-12-12 10:08:50",
                "customer" => "Nina Valencia",
                "address1" => "9637 Mollis Road",
                "city" => "Pont-de-Loup",
                "postcode" => "25648-577",
                "country" => "Tonga",
                "amount" => 1615,
                "status" => "pending",
                "deleted" => "No",
                "last_modified" => "2019-06-04 03:34:32"
            ],
            [
                "id" => 1036,
                "date" => "2020-09-17 14:42:57",
                "customer" => "Rowan Mendez",
                "address1" => "7774 Non St.",
                "city" => "Samsun",
                "postcode" => "4982",
                "country" => "Virgin Islands, British",
                "amount" => 3823,
                "status" => "cancelled",
                "deleted" => "No",
                "last_modified" => "2019-12-31 02:58:59"
            ],
            [
                "id" => 1037,
                "date" => "2019-09-22 20:11:56",
                "customer" => "Victoria Fuentes",
                "address1" => "P.O. Box 303, 108 Sit Road",
                "city" => "Yerbas Buenas",
                "postcode" => "299442",
                "country" => "Madagascar",
                "amount" => 3557,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2020-09-11 15:34:03"
            ],
            [
                "id" => 1038,
                "date" => "2019-06-13 06:40:51",
                "customer" => "Joelle Hudson",
                "address1" => "P.O. Box 465, 9929 Sapien. Ave",
                "city" => "Motta Visconti",
                "postcode" => "762423",
                "country" => "Dominica",
                "amount" => 6594,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2019-11-13 19:52:41"
            ],
            [
                "id" => 1039,
                "date" => "2020-03-26 20:36:41",
                "customer" => "Vivian Rosario",
                "address1" => "6041 Cras Rd.",
                "city" => "Henderson",
                "postcode" => "60167",
                "country" => "Japan",
                "amount" => 3239,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2019-12-22 14:14:00"
            ],
            [
                "id" => 1040,
                "date" => "2019-11-08 19:40:51",
                "customer" => "Dora Blevins",
                "address1" => "P.O. Box 846, 5041 Ultrices. St.",
                "city" => "Ripalta Guerina",
                "postcode" => "471363",
                "country" => "Namibia",
                "amount" => 3596,
                "status" => "pending",
                "deleted" => "No",
                "last_modified" => "2021-04-16 08:00:15"
            ],
            [
                "id" => 1041,
                "date" => "2020-07-02 13:35:12",
                "customer" => "Raya Guerra",
                "address1" => "968-8635 In St.",
                "city" => "Ganshoren",
                "postcode" => "94264",
                "country" => "Chad",
                "amount" => 6702,
                "status" => "in_production",
                "deleted" => "Yes",
                "last_modified" => "2020-10-07 03:27:06"
            ],
            [
                "id" => 1042,
                "date" => "2020-03-31 19:57:53",
                "customer" => "Vera Adkins",
                "address1" => "946-5117 Lacus. Rd.",
                "city" => "Malvern",
                "postcode" => "902243",
                "country" => "Paraguay",
                "amount" => 7175,
                "status" => "cancelled",
                "deleted" => "No",
                "last_modified" => "2019-06-16 08:35:08"
            ],
            [
                "id" => 1043,
                "date" => "2019-06-04 02:37:14",
                "customer" => "Genevieve Ayala",
                "address1" => "Ap #451-319 Aliquam, Rd.",
                "city" => "Satna",
                "postcode" => "2162",
                "country" => "Greece",
                "amount" => 3280,
                "status" => "cancelled",
                "deleted" => "No",
                "last_modified" => "2021-04-01 17:10:49"
            ],
            [
                "id" => 1044,
                "date" => "2019-08-16 10:15:55",
                "customer" => "Suki Mckinney",
                "address1" => "8598 Urna. Rd.",
                "city" => "Noragugume",
                "postcode" => "01103",
                "country" => "Saudi Arabia",
                "amount" => 4368,
                "status" => "cancelled",
                "deleted" => "No",
                "last_modified" => "2020-05-20 15:19:10"
            ],
            [
                "id" => 1045,
                "date" => "2020-09-11 17:36:50",
                "customer" => "Kirestin Chavez",
                "address1" => "Ap #408-5384 Non, Road",
                "city" => "Bursa",
                "postcode" => "64-375",
                "country" => "Russian Federation",
                "amount" => 7291,
                "status" => "pending",
                "deleted" => "No",
                "last_modified" => "2020-12-11 01:05:06"
            ],
            [
                "id" => 1046,
                "date" => "2021-01-11 18:04:49",
                "customer" => "Rinah Perry",
                "address1" => "250 Accumsan St.",
                "city" => "São José dos Pinhais",
                "postcode" => "99113-55095",
                "country" => "Papua New Guinea",
                "amount" => 2546,
                "status" => "in_production",
                "deleted" => "Yes",
                "last_modified" => "2019-08-05 16:23:43"
            ],
            [
                "id" => 1047,
                "date" => "2020-12-18 01:37:17",
                "customer" => "Jillian Owens",
                "address1" => "7476 Nam Rd.",
                "city" => "Maransart",
                "postcode" => "2916",
                "country" => "Bermuda",
                "amount" => 9444,
                "status" => "pending",
                "deleted" => "No",
                "last_modified" => "2020-02-27 17:05:15"
            ],
            [
                "id" => 1048,
                "date" => "2020-12-01 05:25:48",
                "customer" => "Cathleen Patton",
                "address1" => "850-708 Metus Street",
                "city" => "Karachi",
                "postcode" => "S8S 8B2",
                "country" => "Somalia",
                "amount" => 4301,
                "status" => "pending",
                "deleted" => "No",
                "last_modified" => "2020-05-27 16:35:15"
            ],
            [
                "id" => 1049,
                "date" => "2020-01-09 18:28:14",
                "customer" => "Ori Combs",
                "address1" => "Ap #418-2752 Massa Av.",
                "city" => "Renca",
                "postcode" => "10140",
                "country" => "Niue",
                "amount" => 9012,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2019-11-25 19:01:56"
            ],
            [
                "id" => 1050,
                "date" => "2020-07-23 00:15:32",
                "customer" => "Penelope Galloway",
                "address1" => "P.O. Box 493, 8539 Faucibus Ave",
                "city" => "Mesa",
                "postcode" => "419431",
                "country" => "Canada",
                "amount" => 6614,
                "status" => "pending",
                "deleted" => "No",
                "last_modified" => "2019-12-17 22:17:05"
            ],
            [
                "id" => 1051,
                "date" => "2019-12-18 01:30:57",
                "customer" => "Maile Hancock",
                "address1" => "8471 Consequat St.",
                "city" => "Copiapó",
                "postcode" => "60007",
                "country" => "Paraguay",
                "amount" => 7071,
                "status" => "pending",
                "deleted" => "No",
                "last_modified" => "2019-09-14 01:31:15"
            ],
            [
                "id" => 1052,
                "date" => "2019-10-27 14:21:41",
                "customer" => "Teagan Ballard",
                "address1" => "Ap #506-1512 Viverra. Ave",
                "city" => "Millet",
                "postcode" => "51680",
                "country" => "Sao Tome and Principe",
                "amount" => 6433,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2020-05-09 06:01:59"
            ],
            [
                "id" => 1053,
                "date" => "2019-05-13 08:15:32",
                "customer" => "Charissa Dickson",
                "address1" => "P.O. Box 848, 6491 Fusce Ave",
                "city" => "Emines",
                "postcode" => "91726",
                "country" => "Heard Island and Mcdonald Islands",
                "amount" => 6132,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2020-11-30 16:45:23"
            ],
            [
                "id" => 1054,
                "date" => "2020-03-06 06:36:32",
                "customer" => "Brynn King",
                "address1" => "Ap #442-4205 Sed Avenue",
                "city" => "Wekweti",
                "postcode" => "Z1395",
                "country" => "Bermuda",
                "amount" => 2243,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2019-12-19 19:37:26"
            ],
            [
                "id" => 1055,
                "date" => "2020-10-07 09:31:00",
                "customer" => "Haley Nelson",
                "address1" => "5156 Eu Rd.",
                "city" => "Castel di Tora",
                "postcode" => "82917",
                "country" => "Bermuda",
                "amount" => 3358,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2021-04-26 07:08:48"
            ],
            [
                "id" => 1056,
                "date" => "2020-01-24 12:37:28",
                "customer" => "Germane Moore",
                "address1" => "P.O. Box 705, 655 Eu, Rd.",
                "city" => "Cametá",
                "postcode" => "40540",
                "country" => "Puerto Rico",
                "amount" => 5183,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2020-11-15 02:43:41"
            ],
            [
                "id" => 1057,
                "date" => "2019-05-14 23:00:37",
                "customer" => "Lee Williamson",
                "address1" => "562-867 Donec Av.",
                "city" => "Gibsons",
                "postcode" => "690477",
                "country" => "Ethiopia",
                "amount" => 4194,
                "status" => "in_production",
                "deleted" => "Yes",
                "last_modified" => "2021-03-17 01:46:59"
            ],
            [
                "id" => 1058,
                "date" => "2021-03-02 11:16:24",
                "customer" => "Lydia Barr",
                "address1" => "P.O. Box 317, 2172 Ridiculus Av.",
                "city" => "Zaria",
                "postcode" => "95582",
                "country" => "Svalbard and Jan Mayen Islands",
                "amount" => 3200,
                "status" => "in_production",
                "deleted" => "Yes",
                "last_modified" => "2019-07-20 11:24:05"
            ],
            [
                "id" => 1059,
                "date" => "2019-09-13 13:02:55",
                "customer" => "Uma Casey",
                "address1" => "Ap #674-2399 Proin Avenue",
                "city" => "Thurso",
                "postcode" => "38-208",
                "country" => "Greenland",
                "amount" => 3775,
                "status" => "in_production",
                "deleted" => "Yes",
                "last_modified" => "2019-10-08 18:21:02"
            ],
            [
                "id" => 1060,
                "date" => "2020-11-23 15:53:54",
                "customer" => "Joan Boyle",
                "address1" => "5217 Neque Avenue",
                "city" => "La Cruz",
                "postcode" => "59012",
                "country" => "Poland",
                "amount" => 9724,
                "status" => "cancelled",
                "deleted" => "No",
                "last_modified" => "2019-11-26 19:44:40"
            ],
            [
                "id" => 1061,
                "date" => "2020-06-17 16:11:23",
                "customer" => "Miranda Villarreal",
                "address1" => "Ap #329-3363 Suspendisse Rd.",
                "city" => "Dworp",
                "postcode" => "70439",
                "country" => "Israel",
                "amount" => 7947,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2021-01-19 02:38:24"
            ],
            [
                "id" => 1062,
                "date" => "2020-02-12 21:36:10",
                "customer" => "Winter Butler",
                "address1" => "Ap #986-2436 Donec Av.",
                "city" => "Maria",
                "postcode" => "Z4994",
                "country" => "Solomon Islands",
                "amount" => 9351,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2020-02-08 23:38:27"
            ],
            [
                "id" => 1063,
                "date" => "2019-12-14 18:43:35",
                "customer" => "Maya Walls",
                "address1" => "Ap #978-2148 Et St.",
                "city" => "Suncheon",
                "postcode" => "0052 DL",
                "country" => "Japan",
                "amount" => 5113,
                "status" => "pending",
                "deleted" => "No",
                "last_modified" => "2020-06-22 03:32:46"
            ],
            [
                "id" => 1064,
                "date" => "2019-11-21 09:20:57",
                "customer" => "Geraldine Cunningham",
                "address1" => "1064 Curabitur Rd.",
                "city" => "Bad Vilbel",
                "postcode" => "887845",
                "country" => "Ghana",
                "amount" => 3184,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2020-09-28 12:18:38"
            ],
            [
                "id" => 1065,
                "date" => "2020-06-23 06:17:18",
                "customer" => "Teegan Dillon",
                "address1" => "387-7228 Magna Street",
                "city" => "Annapolis",
                "postcode" => "118571",
                "country" => "Portugal",
                "amount" => 2450,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2019-10-20 14:22:49"
            ],
            [
                "id" => 1066,
                "date" => "2020-10-10 22:04:23",
                "customer" => "Alexandra Payne",
                "address1" => "P.O. Box 416, 4112 Donec Street",
                "city" => "Cúcuta",
                "postcode" => "7805",
                "country" => "Palestine, State of",
                "amount" => 7818,
                "status" => "pending",
                "deleted" => "No",
                "last_modified" => "2020-11-19 10:24:25"
            ],
            [
                "id" => 1067,
                "date" => "2020-09-14 10:38:34",
                "customer" => "Belle Mcdowell",
                "address1" => "Ap #573-9644 Vitae, Street",
                "city" => "Gangtok",
                "postcode" => "Z4839",
                "country" => "Samoa",
                "amount" => 4480,
                "status" => "cancelled",
                "deleted" => "No",
                "last_modified" => "2019-05-17 12:17:32"
            ],
            [
                "id" => 1068,
                "date" => "2020-01-14 08:42:22",
                "customer" => "Sheila Ware",
                "address1" => "4425 Quis St.",
                "city" => "Soledad de Graciano Sánchez",
                "postcode" => "4146",
                "country" => "Paraguay",
                "amount" => 5946,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2019-07-27 20:22:53"
            ],
            [
                "id" => 1069,
                "date" => "2020-05-15 23:00:49",
                "customer" => "Gay Morrison",
                "address1" => "1179 Nulla. Rd.",
                "city" => "San Lorenzo Nuovo",
                "postcode" => "702530",
                "country" => "Thailand",
                "amount" => 5511,
                "status" => "pending",
                "deleted" => "No",
                "last_modified" => "2019-05-27 15:09:41"
            ],
            [
                "id" => 1070,
                "date" => "2020-12-08 02:11:15",
                "customer" => "Virginia Harvey",
                "address1" => "Ap #219-7023 Est Rd.",
                "city" => "Grimaldi",
                "postcode" => "2242",
                "country" => "Czech Republic",
                "amount" => 2387,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2021-01-10 21:47:49"
            ],
            [
                "id" => 1071,
                "date" => "2019-10-02 09:19:32",
                "customer" => "Tanya Richard",
                "address1" => "799-5863 Parturient Avenue",
                "city" => "Sorradile",
                "postcode" => "7434",
                "country" => "Guam",
                "amount" => 8630,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2021-04-28 17:23:40"
            ],
            [
                "id" => 1072,
                "date" => "2020-10-28 05:46:29",
                "customer" => "Kaitlin Bryant",
                "address1" => "495-3219 Dignissim Rd.",
                "city" => "Glasgow",
                "postcode" => "97754",
                "country" => "Antarctica",
                "amount" => 9686,
                "status" => "pending",
                "deleted" => "No",
                "last_modified" => "2019-06-29 19:40:11"
            ],
            [
                "id" => 1073,
                "date" => "2020-01-08 18:43:18",
                "customer" => "Evelyn Camacho",
                "address1" => "Ap #102-2440 Amet Rd.",
                "city" => "Cinco Esquinas",
                "postcode" => "41400",
                "country" => "Guernsey",
                "amount" => 4443,
                "status" => "pending",
                "deleted" => "No",
                "last_modified" => "2021-04-12 07:44:59"
            ],
            [
                "id" => 1074,
                "date" => "2019-11-01 19:32:40",
                "customer" => "Elaine Reilly",
                "address1" => "Ap #188-7449 At St.",
                "city" => "Kilsyth",
                "postcode" => "1902",
                "country" => "Barbados",
                "amount" => 5876,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2019-07-04 00:49:10"
            ],
            [
                "id" => 1075,
                "date" => "2020-08-07 13:53:49",
                "customer" => "Jane Moore",
                "address1" => "7687 Suspendisse Street",
                "city" => "Galashiels",
                "postcode" => "77729",
                "country" => "Venezuela",
                "amount" => 7732,
                "status" => "cancelled",
                "deleted" => "No",
                "last_modified" => "2020-04-02 15:11:19"
            ],
            [
                "id" => 1076,
                "date" => "2019-10-15 13:40:45",
                "customer" => "Heidi Morales",
                "address1" => "7220 Orci Av.",
                "city" => "Firozabad",
                "postcode" => "31874",
                "country" => "Grenada",
                "amount" => 6305,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2020-08-01 01:58:15"
            ],
            [
                "id" => 1077,
                "date" => "2021-02-01 01:53:35",
                "customer" => "Octavia Newton",
                "address1" => "P.O. Box 105, 1547 At Av.",
                "city" => "Malbaie",
                "postcode" => "35508",
                "country" => "Burundi",
                "amount" => 6936,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2021-03-29 01:17:20"
            ],
            [
                "id" => 1078,
                "date" => "2020-07-31 11:24:21",
                "customer" => "Tatiana Mcbride",
                "address1" => "3565 Ligula. Street",
                "city" => "Bathurst",
                "postcode" => "70940",
                "country" => "Bulgaria",
                "amount" => 6975,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2021-05-09 07:05:22"
            ],
            [
                "id" => 1079,
                "date" => "2020-12-03 03:11:37",
                "customer" => "Angelica Wilder",
                "address1" => "P.O. Box 351, 9331 Arcu Ave",
                "city" => "Salzwedel",
                "postcode" => "20067-571",
                "country" => "Montenegro",
                "amount" => 4832,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2019-09-02 19:41:21"
            ],
            [
                "id" => 1080,
                "date" => "2020-10-02 15:57:27",
                "customer" => "Kalia Rosa",
                "address1" => "Ap #993-1697 Nunc. Road",
                "city" => "Sachs Harbour",
                "postcode" => "26834",
                "country" => "Gibraltar",
                "amount" => 1543,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2020-02-15 05:57:54"
            ],
            [
                "id" => 1081,
                "date" => "2019-08-28 22:46:29",
                "customer" => "Deanna Santiago",
                "address1" => "P.O. Box 918, 8285 Interdum Av.",
                "city" => "Bonnyville",
                "postcode" => "104130",
                "country" => "Guinea",
                "amount" => 3635,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2020-03-31 15:09:14"
            ],
            [
                "id" => 1082,
                "date" => "2019-06-06 04:53:11",
                "customer" => "Alana Carter",
                "address1" => "P.O. Box 571, 7557 Convallis Ave",
                "city" => "Bandung",
                "postcode" => "646907",
                "country" => "Myanmar",
                "amount" => 8733,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2020-04-17 07:45:43"
            ],
            [
                "id" => 1083,
                "date" => "2020-06-19 16:42:28",
                "customer" => "Xena Gross",
                "address1" => "P.O. Box 833, 2901 Ante. Avenue",
                "city" => "San Rafael",
                "postcode" => "80273",
                "country" => "Tunisia",
                "amount" => 8495,
                "status" => "in_production",
                "deleted" => "Yes",
                "last_modified" => "2020-06-01 01:58:27"
            ],
            [
                "id" => 1084,
                "date" => "2019-11-09 02:54:07",
                "customer" => "Daphne Emerson",
                "address1" => "Ap #500-9767 Facilisis Avenue",
                "city" => "Tirupati",
                "postcode" => "46093",
                "country" => "Haiti",
                "amount" => 2121,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2020-04-09 05:38:46"
            ],
            [
                "id" => 1085,
                "date" => "2021-02-23 14:53:49",
                "customer" => "Robin Clarke",
                "address1" => "Ap #316-8396 Ante Ave",
                "city" => "Åkersberga",
                "postcode" => "45806",
                "country" => "Niue",
                "amount" => 5048,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2019-12-04 04:01:57"
            ],
            [
                "id" => 1086,
                "date" => "2020-07-03 10:21:24",
                "customer" => "Xaviera Allen",
                "address1" => "9074 Lorem Street",
                "city" => "Pelago",
                "postcode" => "20117",
                "country" => "Poland",
                "amount" => 3093,
                "status" => "cancelled",
                "deleted" => "No",
                "last_modified" => "2021-03-01 00:38:47"
            ],
            [
                "id" => 1087,
                "date" => "2019-11-12 17:28:03",
                "customer" => "Kylie Martinez",
                "address1" => "7942 Urna. Rd.",
                "city" => "Fochabers",
                "postcode" => "592908",
                "country" => "Central African Republic",
                "amount" => 2876,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2021-02-27 11:19:34"
            ],
            [
                "id" => 1088,
                "date" => "2020-01-04 12:20:54",
                "customer" => "Quinn Carlson",
                "address1" => "3218 Neque St.",
                "city" => "Grey County",
                "postcode" => "74033",
                "country" => "Madagascar",
                "amount" => 4560,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2020-02-21 02:27:45"
            ],
            [
                "id" => 1089,
                "date" => "2020-04-16 06:45:55",
                "customer" => "Harriet Hendricks",
                "address1" => "P.O. Box 822, 2912 Feugiat Av.",
                "city" => "Paita",
                "postcode" => "99162",
                "country" => "Denmark",
                "amount" => 8017,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2020-08-09 01:19:04"
            ],
            [
                "id" => 1090,
                "date" => "2020-05-17 18:38:40",
                "customer" => "Sierra Meyer",
                "address1" => "Ap #662-9665 Nunc. Ave",
                "city" => "Iowa City",
                "postcode" => "700389",
                "country" => "Sri Lanka",
                "amount" => 2976,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2020-02-26 09:11:41"
            ],
            [
                "id" => 1091,
                "date" => "2019-12-25 22:35:38",
                "customer" => "Jenna Suarez",
                "address1" => "P.O. Box 868, 1476 Cursus. St.",
                "city" => "Guildford",
                "postcode" => "10602",
                "country" => "Mozambique",
                "amount" => 6561,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2019-06-23 03:31:58"
            ],
            [
                "id" => 1092,
                "date" => "2020-03-28 04:12:53",
                "customer" => "Ila Harrison",
                "address1" => "2172 In Av.",
                "city" => "Tula",
                "postcode" => "94190",
                "country" => "Cape Verde",
                "amount" => 3958,
                "status" => "in_production",
                "deleted" => "Yes",
                "last_modified" => "2019-06-22 18:08:17"
            ],
            [
                "id" => 1093,
                "date" => "2019-10-07 14:30:02",
                "customer" => "Jessica Briggs",
                "address1" => "Ap #814-848 Magna. Road",
                "city" => "El Tambo",
                "postcode" => "17474",
                "country" => "Saint Lucia",
                "amount" => 4138,
                "status" => "pending",
                "deleted" => "Yes",
                "last_modified" => "2019-11-22 22:13:51"
            ],
            [
                "id" => 1094,
                "date" => "2019-09-19 03:03:01",
                "customer" => "Noelle Estrada",
                "address1" => "540 Malesuada Rd.",
                "city" => "Lewiston",
                "postcode" => "54517",
                "country" => "Singapore",
                "amount" => 3281,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2019-12-24 19:18:46"
            ],
            [
                "id" => 1095,
                "date" => "2019-09-03 13:18:25",
                "customer" => "Yeo Ramsey",
                "address1" => "1532 Eget Road",
                "city" => "Castri di Lecce",
                "postcode" => "I99 7GL",
                "country" => "Lesotho",
                "amount" => 8833,
                "status" => "cancelled",
                "deleted" => "Yes",
                "last_modified" => "2019-08-24 16:44:38"
            ],
            [
                "id" => 1096,
                "date" => "2020-01-08 07:47:51",
                "customer" => "Yael Vaughan",
                "address1" => "7779 Tortor Rd.",
                "city" => "Sulzbach",
                "postcode" => "74718",
                "country" => "Western Sahara",
                "amount" => 6560,
                "status" => "in_production",
                "deleted" => "Yes",
                "last_modified" => "2020-11-19 13:09:42"
            ],
            [
                "id" => 1097,
                "date" => "2020-03-25 23:16:36",
                "customer" => "Quyn Nixon",
                "address1" => "3879 Orci Road",
                "city" => "Córdoba",
                "postcode" => "25682",
                "country" => "Pakistan",
                "amount" => 7158,
                "status" => "pending",
                "deleted" => "No",
                "last_modified" => "2021-01-26 19:31:16"
            ],
            [
                "id" => 1098,
                "date" => "2019-12-14 19:32:45",
                "customer" => "Aphrodite Olson",
                "address1" => "5104 Ipsum. Rd.",
                "city" => "Busan",
                "postcode" => "778606",
                "country" => "Azerbaijan",
                "amount" => 4869,
                "status" => "in_production",
                "deleted" => "No",
                "last_modified" => "2019-06-26 15:22:20"
            ],
            [
                "id" => 1099,
                "date" => "2019-06-27 02:19:01",
                "customer" => "Delilah Whitfield",
                "address1" => "P.O. Box 268, 6132 Iaculis St.",
                "city" => "Caerphilly",
                "postcode" => "2295",
                "country" => "Poland",
                "amount" => 6501,
                "status" => "in_production",
                "deleted" => "Yes",
                "last_modified" => "2021-03-19 11:05:55"
            ]
        ]);
    }

    /**
     * @Route("/movies", methods="POST")
     */
    public function cancel(Request $request)
    {
        $request = $this->transformJsonBody($request);

        if (! $request) {
            return $this->respondValidationError('Please provide a valid request!');
        }

        return $this->respondCancelled(['cancelled' => 'ok']);
    }
}